import {
  IconAlertTriangle,
  IconBell,
  IconChartBar,
  IconCheck,
  IconChevronRight,
  IconChevronsLeft,
  IconChevronsRight,
  IconCircleCheck,
  IconCircleX,
  IconClock,
  IconCloudUpload,
  IconDatabaseCog,
  IconDiscount2,
  IconFileInvoice,
  IconFileSpreadsheet,
  IconInbox,
  IconLayoutDashboard,
  IconLogout,
  IconMenu2,
  IconMoon,
  IconRefresh,
  IconSearch,
  IconSettings,
  IconSun,
  IconTruckDelivery,
  IconUser,
  IconUsersGroup,
  IconWallet,
  IconX,
  TablerIcon,
} from '@tabler/icons-angular';

// Maps the kebab-case icon keys used in NavItem/config to Tabler icon data
// objects, so config files stay framework-icon-agnostic strings.
export const ICON_REGISTRY: Record<string, TablerIcon> = {
  'layout-dashboard': IconLayoutDashboard,
  wallet: IconWallet,
  'discount-2': IconDiscount2,
  'file-invoice': IconFileInvoice,
  'truck-delivery': IconTruckDelivery,
  'chart-bar': IconChartBar,
  'users-group': IconUsersGroup,
  'database-cog': IconDatabaseCog,
  menu: IconMenu2,
  'chevrons-left': IconChevronsLeft,
  'chevrons-right': IconChevronsRight,
  search: IconSearch,
  bell: IconBell,
  sun: IconSun,
  moon: IconMoon,
  user: IconUser,
  logout: IconLogout,
  settings: IconSettings,
  'alert-triangle': IconAlertTriangle,
  inbox: IconInbox,
  'chevron-right': IconChevronRight,
  x: IconX,
  check: IconCheck,
  clock: IconClock,
  'cloud-upload': IconCloudUpload,
  'circle-check': IconCircleCheck,
  'circle-x': IconCircleX,
  refresh: IconRefresh,
  'file-spreadsheet': IconFileSpreadsheet,
};
