import {
  IconAlertTriangle,
  IconBell,
  IconChartBar,
  IconCheck,
  IconChevronRight,
  IconChevronsLeft,
  IconChevronsRight,
  IconCircleCheck,
  IconCircleX,
  IconClock,
  IconCloudUpload,
  IconCopy,
  IconDatabaseCog,
  IconDiscount2,
  IconFileInvoice,
  IconFilter,
  IconFileSpreadsheet,
  IconInbox,
  IconLayoutDashboard,
  IconLogout,
  IconMenu2,
  IconMinus,
  IconMoon,
  IconPlayerPause,
  IconPlayerPlay,
  IconRefresh,
  IconSearch,
  IconSettings,
  IconSun,
  IconTrendingDown,
  IconTrendingUp,
  IconTruckDelivery,
  IconAlertCircle,
  IconArrowLeft,
  IconArrowRight,
  IconArrowsExchange,
  IconBolt,
  IconBuildingWarehouse,
  IconCalendarRepeat,
  IconCash,
  IconChevronDown,
  IconCircleDot,
  IconDeviceDesktop,
  IconDots,
  IconDownload,
  IconEdit,
  IconExternalLink,
  IconEye,
  IconFiles,
  IconFlag,
  IconGauge,
  IconHelp,
  IconHistory,
  IconInfoCircle,
  IconKey,
  IconListSearch,
  IconLock,
  IconLockOpen,
  IconMail,
  IconMapPin,
  IconPencil,
  IconPlugConnected,
  IconPlus,
  IconRoute,
  IconShieldLock,
  IconShoppingCart,
  IconTag,
  IconTransfer,
  IconTrash,
  IconUserCircle,
  IconUser,
  IconUserPlus,
  IconUsersGroup,
  IconWallet,
  IconX,
  TablerIcon,
} from '@tabler/icons-angular';

// Maps the kebab-case icon keys used in NavItem/config to Tabler icon data
// objects, so config files stay framework-icon-agnostic strings.
export const ICON_REGISTRY: Record<string, TablerIcon> = {
  'layout-dashboard': IconLayoutDashboard,
  wallet: IconWallet,
  'discount-2': IconDiscount2,
  'file-invoice': IconFileInvoice,
  filter: IconFilter,
  'truck-delivery': IconTruckDelivery,
  'chart-bar': IconChartBar,
  'users-group': IconUsersGroup,
  'database-cog': IconDatabaseCog,
  menu: IconMenu2,
  'chevrons-left': IconChevronsLeft,
  'chevrons-right': IconChevronsRight,
  search: IconSearch,
  bell: IconBell,
  sun: IconSun,
  moon: IconMoon,
  user: IconUser,
  logout: IconLogout,
  settings: IconSettings,
  'alert-triangle': IconAlertTriangle,
  inbox: IconInbox,
  'chevron-right': IconChevronRight,
  x: IconX,
  check: IconCheck,
  clock: IconClock,
  'cloud-upload': IconCloudUpload,
  'circle-check': IconCircleCheck,
  'circle-x': IconCircleX,
  refresh: IconRefresh,
  'file-spreadsheet': IconFileSpreadsheet,
  copy: IconCopy,
  'player-play': IconPlayerPlay,
  'player-pause': IconPlayerPause,
  // Delta indicators on dashboard stat tiles and breakdown rows.
  'trending-up': IconTrendingUp,
  'trending-down': IconTrendingDown,
  minus: IconMinus,
  'user-plus': IconUserPlus,

  // ─── Administration 1.0 ────────────────────────────────────────────────────
  // Destinations produced by the menu fold (see core/menu/menu-blueprint.ts) plus the
  // action icons the Administration screens use. `circle-dot` is the deliberate
  // fallback for a legacy menu row whose icon we do not recognise — see
  // SidebarComponent.iconFor, which never renders a blank glyph.
  'circle-dot': IconCircleDot,
  'shield-lock': IconShieldLock,
  route: IconRoute,
  transfer: IconTransfer,
  history: IconHistory,
  'plug-connected': IconPlugConnected,
  'user-circle': IconUserCircle,
  'menu-2': IconMenu2,
  'calendar-repeat': IconCalendarRepeat,
  'list-search': IconListSearch,

  // Legacy FontAwesome 4 icon names map onto these — see FA4_TO_TABLER.
  pencil: IconPencil,
  mail: IconMail,
  files: IconFiles,
  bolt: IconBolt,
  gauge: IconGauge,
  'shopping-cart': IconShoppingCart,
  'device-desktop': IconDeviceDesktop,
  flag: IconFlag,
  cash: IconCash,
  help: IconHelp,
  'building-warehouse': IconBuildingWarehouse,

  // Action + state icons used across the Administration screens.
  plus: IconPlus,
  edit: IconEdit,
  trash: IconTrash,
  eye: IconEye,
  key: IconKey,
  lock: IconLock,
  'lock-open': IconLockOpen,
  download: IconDownload,
  'chevron-down': IconChevronDown,
  'arrow-left': IconArrowLeft,
  'arrow-right': IconArrowRight,
  'arrows-exchange': IconArrowsExchange,
  'external-link': IconExternalLink,
  'alert-circle': IconAlertCircle,
  'info-circle': IconInfoCircle,
  'map-pin': IconMapPin,
  tag: IconTag,
  dots: IconDots,
};
