import { UserContext } from './user-context.model';

// Fixture users for the mock role switcher (CLAUDE.md §3 Auth). One per role so
// Talal can validate screen access without logging out. Keyed by role for lookup
// from the dev panel.
export const MOCK_USERS: Record<string, UserContext> = {
  RSM: {
    userId: 'u-rsm-01',
    name: 'Ahmed Bilal',
    roles: ['RSM'],
    regions: ['Punjab-North', 'Punjab-South'],
    brands: ['Olpers', 'Tarang'],
    permissions: [
      'BUDGET_VIEW',
      'BUDGET_CREATE',
      'SCHEME_VIEW',
      'SCHEME_CREATE',
      'CLAIMS_VIEW',
      'CLAIMS_APPROVE',
      'DISTRIBUTION_VIEW',
      'REPORTS_VIEW',
    ],
  },
  RMC: {
    userId: 'u-rmc-01',
    name: 'Sara Iqbal',
    roles: ['RMC'],
    regions: ['Punjab-North'],
    brands: ['Olpers'],
    permissions: ['BUDGET_VIEW', 'SCHEME_VIEW', 'SCHEME_CREATE', 'CLAIMS_VIEW', 'REPORTS_VIEW'],
  },
  HEAD_OF_SALES: {
    userId: 'u-hos-01',
    name: 'Farhan Malik',
    roles: ['HEAD_OF_SALES'],
    regions: ['Punjab-North', 'Punjab-South', 'Sindh', 'KPK'],
    brands: ['Olpers', 'Tarang', 'Nurpur'],
    permissions: [
      'BUDGET_VIEW',
      'BUDGET_APPROVE',
      'SCHEME_VIEW',
      'SCHEME_APPROVE',
      'CLAIMS_VIEW',
      'CLAIMS_APPROVE',
      'DISTRIBUTION_VIEW',
      'REPORTS_VIEW',
    ],
  },
  ADMIN: {
    userId: 'u-admin-01',
    name: 'Nida Sheikh',
    roles: ['ADMIN'],
    regions: ['Punjab-North', 'Punjab-South', 'Sindh', 'KPK', 'Balochistan'],
    brands: ['Olpers', 'Tarang', 'Nurpur'],
    permissions: [
      'BUDGET_VIEW',
      'BUDGET_CREATE',
      'BUDGET_APPROVE',
      'SCHEME_VIEW',
      'SCHEME_CREATE',
      'SCHEME_APPROVE',
      'CLAIMS_VIEW',
      'CLAIMS_APPROVE',
      'DISTRIBUTION_VIEW',
      'DISTRIBUTION_MANAGE',
      'REPORTS_VIEW',
      'ADMIN_USER_MANAGE',
      'ADMIN_MASTER_DATA',
    ],
  },
  MIS: {
    userId: 'u-mis-01',
    name: 'Kamran Yousuf',
    roles: ['MIS'],
    regions: ['Punjab-North', 'Punjab-South', 'Sindh', 'KPK', 'Balochistan'],
    brands: ['Olpers', 'Tarang', 'Nurpur'],
    permissions: ['BUDGET_VIEW', 'SCHEME_VIEW', 'CLAIMS_VIEW', 'DISTRIBUTION_VIEW', 'REPORTS_VIEW'],
  },
  TRADE_CATEGORY: {
    userId: 'u-tc-01',
    name: 'Hina Raza',
    roles: ['TRADE_CATEGORY'],
    regions: ['Punjab-North', 'Punjab-South'],
    brands: ['Olpers', 'Tarang'],
    permissions: ['BUDGET_VIEW', 'SCHEME_VIEW', 'SCHEME_CREATE', 'SCHEME_APPROVE', 'REPORTS_VIEW'],
  },
  DISTRIBUTOR: {
    userId: 'u-dist-01',
    name: 'Waqas Distribution Co.',
    roles: ['DISTRIBUTOR'],
    regions: ['Punjab-North'],
    brands: ['Olpers'],
    permissions: ['CLAIMS_VIEW', 'DISTRIBUTION_VIEW'],
  },
};
